apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: {{ .Values.azs }}
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: {{ .Values.iamInstanceProfileId }}
    subnetSelector:
      Name: {{ .Values.eksVpcName }}-private*
    securityGroupSelector:
      karpenter.sh/discovery/{{ .Values.eksClusterId }}: {{ .Values.eksClusterId }}
  labels:
    type: karpenter
    provisioner: default
  taints:
    - key: default
      value: 'true'
      effect: NoSchedule
  ttlSecondsAfterEmpty: 120