apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atlantis
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atlantis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlantis 
subjects:
- kind: ServiceAccount
  name: atlantis
  namespace: atlantis

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlantis
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::321852949023:role/capstone-project-atlantis-irsa
automountServiceAccountToken: false

---
apiVersion: v1
kind: Namespace
metadata:
  name: atlantis