apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: team-jose
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: {{.Values.spec.ingress.host}}
    alb.ingress.kubernetes.io/group.name: team-jose-ingress
spec:
  ingressClassName: alb
  rules:
    - host: {{.Values.spec.ingress.host}}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
    - host: {{.Values.spec.ingress.host}}
      http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: tasks
              port:
                number: 80
  tls:
  - hosts:
    - {{.Values.spec.ingress.host}}
