apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 321852949023.dkr.ecr.us-east-1.amazonaws.com/simple-crud-frontend-app-dev:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1024M
            cpu: 0.5
          limits:
            memory: 2048M
            cpu: 1
