apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
    server: ''
  source:
    repoURL: https://github.com/jamoroso-caylent/eks-blueprints-add-ons
    targetRevision: main
    path: chart
    helm:
      valueFiles:
      - values-{{ .Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true