apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: karpenter
    name: {{ .Values.env }}-workload
    server: ''
  source:
    repoURL: https://github.com/jamoroso-caylent/eks-blueprints-add-ons
    targetRevision: main
    path: chart
    helm:
      valueFiles:
      - values-{{ .Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-operation-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
    server: ''
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/team-operations/{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true