apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1024M
            cpu: 0.5
          limits:
            memory: 2048M
            cpu: 1
      nodeSelector:
        type: karpenter
        provisioner: default
      tolerations:
        - key: 'default'
          operator: 'Exists'
          effect: 'NoSchedule'